server:
  port: 7071
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jorgecahui/SisMunicipio.git
<<<<<<< HEAD:SisMunicipio-dad/Backend/ms-config-server/src/main/resources/application.yml
          searchPaths: SisMunicipio-dad/config-data
          default-label: lunes17
=======
          searchPaths: config-data
          default-label: main
>>>>>>> origin/main:Backend/ms-config-server/src/main/resources/application.yml
  security:
    user:
      name: root
      password: 123456